format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$dart\
$custom\
$java\
$aws\
$env_var\
$line_break\
$jobs\
$battery\
$time\
$status\
$character\
"""

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ](bold red) "

[docker_context]
format = "via [ğŸ³ $context](blue bold)"

[git_commit]
commit_hash_length = 8

[custom.clj]
command = "clojure --help | head -n 1 | awk '{print $2}'"  # shows output of command
files = ["deps.edn"]       # can specify filters
symbol = "Î» clojure"
style = "bold green"
format = "[$symbol $output]($style) "
